name: census_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip=22.1.2
  - pytest=7.1.2
  - jupyterlab=3.4.4
  - ipywidgets=7.6.5
  - pandas=1.4.3
  - pandas-profiling=3.2.0
  - numpy=1.21.5
  - catboost=1.0.6
  - scikit-learn=1.1.1
  - flake8=4.0.1
  - requests=2.28.1
  - pip:
    - fastapi==0.83.0
    - pydantic==1.10.2
    - uvicorn==0.18.3
